### ISSUE TITLE
Tagline contains misspelling

### ISSUE THREAD

**Issue by sjpfenninger** [repolicy/csp-guru#10]
``A database of concentrated solar power plants of the world for energy modellers and analysts.``
--->
``A database of concentrating solar power plants of the world for energy modellers and analysts.``

**Comment by richard-thonig** [comment]
thanks for pointing  this out. I changed it on Zenodo - and will add it for the next version in the datapackage.

**Comment by richard-thonig** [comment]
Changed it.
