### ISSUE TITLE
Change setup to single branch

### ISSUE THREAD

**Issue by sjpfenninger** [repolicy/csp-guru#12]
I think it would make most sense to have a single `master` branch and configure GitHub to serve pages from there rather than from `gh-pages`, as otherwise two branches need to be kept up-to-date with the most current CSV file, which seems like a recipe for mistakes happening at some point.

**Comment by timtroendle** [comment]
True, but we are releasing automatically on Zenodo and didn't want to package and release the website as well. Also it has the advantage that we can update the master branch without updating the website; e.g. incrementally update the data and only when we release the data, we update the website as well.

**Comment by sjpfenninger** [comment]
Yep, that makes sense.. closing this.
