### ISSUE TITLE
Move About Page as extended description to landing page

### ISSUE THREAD

**Issue by richard-thonig** [repolicy/csp-guru#17]
the about page is really double information.
Johan proposed to move it to the main page.

**Comment by richard-thonig** [comment]
@timtroendle :
    All text editors can open .md, even the build in text editors on Mac and Windows. Nevertheless I wouldn't mind switching to .txt -- it's only file suffix nothing more.
    Regarding the .json file, I wouldn't explain all details here to not repeat ourselves. I think we should mainly do three things:
    ** say that we are following the datapackage standard
    ** link to the datapackage standard for more information
    ** say that the dataset is the csv file, and its metadata is in the json

**Comment by timtroendle** [comment]
Related pull request: #16 .
