### ISSUE TITLE
Check list of authors

### ISSUE THREAD

**Issue by timtroendle** [repolicy/csp-guru#49]
Current list of authors is: Richard/Johan as authors, Tim as maintainers. @richard-thonig is this list correct?

**Comment by richard-thonig** [comment]
Falls das nicht doof aussieht: 
Lilliestam@IASS, Thonig@IASS for all entries; Gilmanova@CAS and Zang@CAS for all Chinese entries

**Comment by timtroendle** [comment]
Ich weiss nicht ob das geht und würde die Zuweisung zu einzelnen Einträgen. einfach weglassen.

Das hier ist der aktuelle Eintrag:

```json
"contributors": [
        {
            "title": "Johan Lilliestam",
            "email": "johan.lilliestam@iass-potsdam.de",
            "role": "author"
        },
        {
            "title": "Tim Tröndle",
            "email": "tim.troendle@iass-potsdam.de",
            "role": "maintainer"
        },
        {
            "title": "Richard Thonig",
            "email": "richard.thonig@iass-potsdam.de",
            "role": "author"
        }
    ],
```
Kannst du sie da eintragen und einen PR öffnen?
