### ISSUE TITLE
rename organisation 

### ISSUE THREAD

**Issue by richard-thonig** [repolicy/csp-guru#55]
We still link to rep.ethz.ch on the github organisation.

can we maybe rename it too? probably not, i suppose.

![image](https://user-images.githubusercontent.com/41374623/85743990-cf116f80-b704-11ea-97c7-875fc4a140e9.png)

**Comment by richard-thonig** [comment]
i can't change this because you are the owner, @timtroendle

**Comment by timtroendle** [comment]
I've changed the full name and the logo and all that. I did not change the actual id `repolicy`. Changing this can [break things](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization) and I wouldn't want to do that now. Also, the `repolicy` id is kinda neutral -- it's not `rep` in the end. What do you think?

**Comment by richard-thonig** [comment]
That's alright with me.
