### ISSUE TITLE
Locations are formatted inconsistently

### ISSUE THREAD

**Issue by timtroendle** [repolicy/csp-guru#66]
The locations are given as a string of degree, arcminutes, and arcseconds. However, the formatting is inconsistent between entries. Some come with whitespace, some don't. Some come with [non-breaking whitespace](https://en.wikipedia.org/wiki/Non-breaking_space), some don't. Sometimes arcminutes and -seconds are given using `'` and `"`, sometimes using `′` and `″`. Some use commas to separate latitude and longitude, some don't. This makes handling the data very difficult.

**Comment by richard-thonig** [comment]
I have now changed the coordinates to decimal in 2020-07-01
